name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y jq parallel git curl bash
        else
          brew install jq parallel git curl bash
        fi
        npm install -g bats
    
    - name: Run shellcheck
      run: shellcheck git-mirror.sh lib/*/*.sh config/*.sh
    
    - name: Run unit tests
      run: bats tests/unit/
    
    - name: Run integration tests
      run: bash tests/integration/test_integration.sh
    
    - name: Run load tests
      run: bash tests/load/test_load.sh --dry-run --repos 10 --parallel 2
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}
        path: test-results/