name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Cache dependencies
      id: cache-docs-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm-global
        key: ${{ runner.os }}-docs-deps
        restore-keys: |
          ${{ runner.os }}-docs-deps-
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        
        # Install markdownlint-cli only if not cached
        if ! command -v markdownlint >/dev/null 2>&1; then
          npm install -g markdownlint-cli@latest
        else
          echo "✅ markdownlint already installed (cached)"
        fi
    
    - name: Validate documentation
      run: |
        # Check markdown files
        markdownlint README.md docs/*.md
        
        # Check for broken links
        find . -name "*.md" -exec grep -l "http" {} \; | while read file; do
          echo "Checking links in $file"
          grep -o 'http[^)]*' "$file" | while read url; do
            if ! curl -s --head "$url" | head -1 | grep -q "200 OK"; then
              echo "Warning: Broken link in $file: $url"
            fi
          done
        done
    
    - name: Generate man page
      run: |
        if [ -f docs/git-mirror.1.md ]; then
          pandoc docs/git-mirror.1.md -s -t man -o docs/git-mirror.1
          echo "Man page generated: docs/git-mirror.1"
        else
          echo "No man page source found"
        fi
    
    - name: Update README
      run: |
        if [ -f docs/README.md ]; then
          cp docs/README.md README.md
          echo "README updated from docs/README.md"
        fi
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md docs/git-mirror.1
        git diff --staged --quiet || git commit -m "Update documentation [skip ci]"
        git push
