name: Markdownlint

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Markdownlint
        id: cache-markdownlint
        uses: actions/cache@v4
        with:
          path: ~/.npm-global
          key: ${{ runner.os }}-markdownlint-latest
          restore-keys: |
            ${{ runner.os }}-markdownlint-
      
      - name: Install Markdownlint
        if: steps.cache-markdownlint.outputs.cache-hit != 'true'
        run: |
          npm install -g markdownlint-cli@latest
          echo "✅ markdownlint installed"
      
      - name: Run Markdownlint
        continue-on-error: true
        run: |
          echo "=== Markdownlint sur tous les fichiers Markdown ==="
          markdownlint '**/*.md' --ignore node_modules || true
          
          echo "=== Markdownlint terminé avec succès ==="
