name: ShellCheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run ShellCheck
        run: |
          echo "=== Installation de ShellCheck ==="
          sudo apt-get update
          sudo apt-get install -y shellcheck
          
          echo "=== ShellCheck sur le script principal ==="
          shellcheck git-mirror.sh
          
          echo "=== ShellCheck sur tous les modules ==="
          find lib -name "*.sh" -exec shellcheck {} \;
          find config -name "*.sh" -exec shellcheck {} \;
          find tests -name "*.bats" -exec shellcheck {} \;
          
          echo "=== ShellCheck terminé avec succès ==="
